version: "3"
services:
  db:
    image: "postgres"
    container_name: "pgsql_medidores"
    env_file:
      - ./docker/db/env.sh
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: "medidores:latest"
    depends_on:
      - db
    env_file:
      - ./docker/app/env.sh
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  default:
  backend:
    driver: bridge