version: "3"
services:
  db:

    image: "postgres"

    container_name: "pgsql_medidores"

    environment:
      - POSTGRES_USER=medidores
      - POSTGRES_PASSWORD=medidores
      - POSTGRES_DB=medidores

    ports:
      - "5432:5432"

    networks:
      - backend

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: "medidores:latest"
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  default:
  backend:
    driver: bridge